# Generated by Django 2.0.5 on 2018-11-08 01:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artical_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artical_title', models.CharField(default='', max_length=100)),
                ('artical_type', models.CharField(default='', max_length=100)),
                ('artical_add_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('artical_mod_date', models.DateTimeField(auto_now=True)),
                ('artical_content', models.TextField(blank=True, default='')),
            ],
        ),
    ]
