# Generated by Django 2.0.5 on 2018-11-08 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artical_model',
            old_name='artical_add_data',
            new_name='artical_add_date',
        ),
    ]
