# Generated by Django 2.0.5 on 2018-08-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemList', '0003_auto_20180806_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='商品名稱'),
        ),
        migrations.AlterField(
            model_name='item',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.URLField(blank=True, default='', verbose_name='照片URL'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='商品價格'),
        ),
        migrations.AlterField(
            model_name='item',
            name='seller',
            field=models.CharField(default='', max_length=100, verbose_name='賣家'),
        ),
    ]
