# Generated by Django 2.0.5 on 2018-08-30 17:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_auto_20180831_0117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_account',
            new_name='user_detail',
        ),
    ]
