# Generated by Django 2.0.5 on 2018-08-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='商品名稱')),
                ('price', models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='商品價格')),
                ('content', models.TextField(blank=True, default='', verbose_name='備註')),
                ('photo', models.ImageField(upload_to='img')),
                ('seller', models.CharField(default='', max_length=100, verbose_name='賣家')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='更新時間')),
            ],
        ),
    ]
