# Generated by Django 2.0.5 on 2018-08-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Identity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='商品Id'),
        ),
    ]
